version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
  nginx:
    build: containers/nginx
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:

